### ISSUE TITLE
[Bug]:简要描述你的问题

### ISSUE THREAD

**Issue by orange1988** [Wanxp/obsidian-douban#102]
<img width="331" alt="image" src="https://github.com/Wanxp/obsidian-douban/assets/1501620/c56e2393-dee5-4264-b93f-fd0e0bb939cb">

出现该错误

**Comment by Wanxp** [comment]
提供下搜索的主题

**Comment by orange1988** [comment]
> 提供下搜索的主题

尝试了“全部”和“书籍”

**Comment by Wanxp** [comment]
重新登录有效果吗

**Comment by Wanxp** [comment]
长时间没有回应，关闭issue

**Comment by orange1988** [comment]
> 重新登录有效果吗

没有
