### ISSUE TITLE
增加图床或网络图片功能

### ISSUE THREAD

**Issue by Kiss-World** [Wanxp/obsidian-douban#103]
目前使用的是 auto load image 插件 ，可以把图片上传的图床。能否让豆瓣的下载的图片直接上传到图床。

备选方案：直接获取 豆瓣封面的网络地址。

**Comment by Wanxp** [comment]
图床可能比较难搞，涉及到上传权限和格式的问题，后续我想个方案，不过你这个想法不错，确实利用自己的图床能规避后续使用豆瓣链接以及如果存在本地导致臃肿问题

**Comment by Wanxp** [comment]
已经增加了PicGo图床功能
