### ISSUE TITLE
[Bug]:豆瓣同步结果→“同步结果明细”的输出，文件名没有按照定义的格式输出

### ISSUE THREAD

**Issue by weqoocu** [Wanxp/obsidian-douban#104]
自己定义的文件名格式是：{{title}}-{{id}}
<img width="817" alt="image" src="https://github.com/Wanxp/obsidian-douban/assets/35360006/c6504c29-d723-4c6d-b09c-af75f2ed6173">

输出的格式是：{{title}}
<img width="586" alt="image" src="https://github.com/Wanxp/obsidian-douban/assets/35360006/b2f794eb-6924-4cab-96c7-1ac5941703a4">

因为没有对应的双链，obsidian会显示文件没有创建，实际是有创建，只是文件名格式不对

**Comment by Wanxp** [comment]
第一，是否同步之前已经有了对应的同名文件，所以后面状态显示 未替换
其二，你把文件名设置中的横杠替换成下换线试下，看能否生效

**Comment by weqoocu** [comment]
> 第一，是否同步之前已经有了对应的同名文件，所以后面状态显示 未替换 其二，你把文件名设置中的横杠替换成下换线试下，看能否生效

/是文件把设置把， 换成横杆，那不是没有文件夹了

**Comment by Wanxp** [comment]
为下划线，使用 “_”代替“-”试下效果
