### ISSUE TITLE
标签建议、描述和副标题提取问题

### ISSUE THREAD

**Issue by StrollStars** [Wanxp/obsidian-douban#11]
1.目前书籍获取元数据后，只会增加标签Book，可否增加作者？

2.如果获取到的描述含有换行，则元数据阅览模式会报错，引入的时候可否过滤掉换行？
PS：获取的描述比网页能看到的要少。

3.发现书籍的副标题信息提取不到。

**Comment by StrollStars** [comment]
1.感谢指教，另发现新版的模版有调整，图片放到元数据里去了，虽然可以手动哦调整，但是考虑到延续，建议还原先前的默认格式。如果我自定义了模版，新版插件覆盖会丢失吗？

2.在元数据区直接用中括号`[]`阅读预览界面会报错，需要加转义符`\`，希望也能一并处理。

3.《越过人生的刀锋》，副标题《金庸女子图鉴》。
https://book.douban.com/subject/35951556/

**Comment by Wanxp** [comment]
1.1 默认模板是否是元数据形式, 这个之前一直在考量是直接文本还是元数据. 主要考虑直接文本图片的效果展示更友好, 而元数据图片展示是个问题. 但我认为核心的问题是这个插件的目的是为了导入 电影的信息, 作为个人数据库数据的一部分, 元数据也许更能体现, 所以你的建议我会仔细考虑的.
1.2 升级插件版本带来的自定义模板是否会有影响, 这个有待验证 .
1.3 图片引用就是引用网络, 应该只要豆瓣还在图片就还在,.考虑有时候因网络故障导致图片链接失效也有可能, 未来会进行优化, 增加选项是否要同步保存图片.
2. 元数据特殊字符导致的失效, 这个会在未来版本进行修复.
3. 副标题 和 页数提取不正常 , 这个会在未来版本进行修复.
4. 增加丛书信息提取, 这个在未来版本也会提供 ,感谢反馈.

**Comment by StrollStars** [comment]
1.1其实考虑到元数据供索引，直接文本供查看，两边提供最好，不过这样会产生数据冗余。
考虑到通过图片可以直观看到对应的书籍，还是把图片放在正文中好，此外图片放在元数据里索引后的表格如果文字简短既不美观，也浪费空间。

**Comment by StrollStars** [comment]
5.有多个作者时只提取了第一个：[彼得·林奇的成功投资](https://book.douban.com/subject/4827219/)

**Comment by Wanxp** [comment]
> 
1.1 决定还是使用元数据形式展示, 结合metatable插件,dataview之类的插件确实会方便使用. 现在最新版本的默认模板都已经修改成元数据形式
2. 目前元数据情况如果具有yaml的特殊字符下会使用""双引号进行包裹,以满足yaml格式需求,  回车会被替换成 句号
3. 《越过人生的刀锋》，副标题《金庸女子图鉴》。现在可以提取出来了。
4.  增加丛书信息(series)参数使用

**Comment by Wanxp** [comment]
> 1.1是直接文本还是元数据我觉得是挺不好取舍的，有没有直接文本整块引用元数据的方法？ 其实我有点偏向豆瓣这种展示模式，就是左边图片，右边是书籍相关信息，是不是Markdown做不到？ 至于图片，我觉得还是放在直接文本中好些，不然Dataview插件生成的表格浪费空间还不好看。 PS：元数据是不是基本就用来被Dataview之类的插件抽取信息用？
> 
> 3.译者如果是两个人，也只提取到了一个人。
> 
> 4.丛书你打算用什么名称？我先跟着改下。
> 
> 5.有多个作者时只提取了第一个：《[彼得·林奇的成功投资](https://book.douban.com/subject/4827219/)》

1.1 默认模板现在是元数据形式
3. 译者是数组问题也修复了
4. 丛书使用的参数是"{{series}}"
5. 作者现在提取了多个

感谢反馈.

**Comment by StrollStars** [comment]
1.1如我前面所述，有办法在正文中做成豆瓣的样子吗？就是左边图片，右边书籍的信息。
1.2我以覆盖的方式更新，发现书籍设置的模板还是原来的，你方便粘贴下新装的书籍模板吗？

2.是不是直接把方括号给去掉了？

4.丛书还没有提取到。

其他问题都修复了。

**Comment by Wanxp** [comment]
1.1 如果要做成豆瓣的样子, 可能需要通过自定义模板来实现了, 按照markdown的语法引入html语法应该是能实现的,这你可以尝试下
1.2 未来版本, 如果将自定义模板清空, 则会使用默认模板导入
2. 作者的国家名称去除了, 使用斜杠代替
4.. 丛书最新版本的可以提取到,你确认下是不是因为模板未配置对,参数是"series"


书籍目前的默认模板
```text
---
doubanId: {{id}}
title: {{title}}
subTitle: {{subTitle}}
originalTitle: {{originalTitle}}
series: {{series}}
type: {{type}}
author: {{author}}
score: {{score}}
datePublished: {{datePublished}}
translator: {{translator}}
publisher: {{publisher}}
isbn: {{isbn}}
url: {{url}}
totalPage: {{totalPage}}
price: {{price}}
tags: Book
binding: {{binding}}
desc: {{desc}}
---

![image|150]({{image}})

{{menu}}

```

**Comment by Wanxp** [comment]
回车换行符的问题确实还在, 当有多行的时候会触发,会在下个版本中修复

**Comment by StrollStars** [comment]
豆瓣的样子看来有点复杂了，那就先不处理了，我也不想把它搞得太复杂。

模板的问题，确实覆盖会保留先前的配置，所以我即使更新了插件也无法获取到丛书信息。
但是我发现另外个问题，如果升级前不清空模板，那是不是只能重新卸载再安装插件，才能得到更新后的默认模板？

**Comment by Wanxp** [comment]
已经修复desc字段回车导致元数据异常问题 [v1.6.0](https://github.com/Wanxp/obsidian-douban/releases/tag/v1.6.0)

**Comment by Wanxp** [comment]
现在模板的配置修改成了使用文件的形式, 旧模板不能使用了. 如果想要使用最新模板则只需点击配置中的复制默认模板,粘贴到模板文件中

**Comment by StrollStars** [comment]
哇，这个版本更新好棒，感谢开发者，已知问题都解决了，至于模板怎么展现，我有更好的想法再发，先关闭了。

**Comment by Wanxp** [comment]
> 哇，这个版本更新好棒，感谢开发者，已知问题都解决了。
> 
> 关于书籍模板，要不要都拿出来不要放在元数据里了？因为元数据是给机器索引的，正文是直接给人看的。 还有就是目录可否下面一行加`---`，也就是让它成为独立一块。

目录下面一行加`---` 这个能否给下模板, 看下效果如何.

**Comment by StrollStars** [comment]
![2022-11-06_212445](https://user-images.githubusercontent.com/10942225/200173341-cd4df343-9db6-47f2-94a4-a2856f3760d7.png)
如上图红框处，也就是实现标题的目的，毕竟正文不可能只有标题对吧？顺带也方便实现层级缩进。
但是我发现自己没办法改模板，因为三横是要加在`{{menu}}`之中。

**Comment by Wanxp** [comment]
加在内容之中, 这个不太好处理, 因为menu是属性值, 要达到修改内容中的效果,得好好看下怎么处理.

**Comment by Wanxp** [comment]
目前这里面的问题都已解决, 关闭issue了
