### ISSUE TITLE
[Bug]:搜索豆瓣创建文档时，显示没有相关插件。（无法搜索到相关内容）

### ISSUE THREAD

**Issue by Shuis004** [Wanxp/obsidian-douban#117]
1. 问题说明

1.1 操作:
使用搜索豆瓣导入书影音时，显示没有相关插件。（无法搜索到相关内容）
尝试过了很多次，只成功过一次，并且搜索同样的名称时再也没有成功过。
![Screenshot 2024-06-02 001607](https://github.com/Wanxp/obsidian-douban/assets/119423302/8c256db9-cd3d-48df-a4ca-32cd65e64190)
![Screenshot 2024-06-02 001237](https://github.com/Wanxp/obsidian-douban/assets/119423302/0bcfe5d9-a43c-4546-8f85-461e4463c898)

1.2 结果:
![Screenshot 2024-06-02 001237](https://github.com/Wanxp/obsidian-douban/assets/119423302/0bcfe5d9-a43c-4546-8f85-461e4463c898)

1.3 我想要的效果:
能够正常搜索并导入。

4. 其它
如相关的插件设置...

5. 操作系统版本
- [x] windows
- [ ] ubuntu
- [ ] mac
- [ ] android
- [ ] ios
6. obisidian版本
...

**Comment by Wanxp** [comment]
选择对应的子类型，比如书籍、电影，看能否搜索到

**Comment by Wanxp** [comment]
尝试在插件中登录豆瓣。
当没有在插件登录豆瓣时，搜索大概率也是空。
这是豆瓣的官方数据自我保护措施之一，未登录时，无法获取到相关内容。

**Comment by Shuis004** [comment]
谢谢你，后面我通过搜索指定类型后成功显示了内容。虽然搜索全部类型还是不可行，但我已经满意了哈哈。
