### ISSUE TITLE
[Bug]:搜索豆瓣并创建文档关键词为中文时报 error

### ISSUE THREAD

**Issue by sayayuka** [Wanxp/obsidian-douban#118]
1. 问题说明

1.1 操作:
Mac Obsidian App Command P，打开命令面板，选择：搜索豆瓣并创建文档，输入中文关键字，App 右上角报错如图。

1.2 结果:
<img width="311" alt="bug" src="https://github.com/Wanxp/obsidian-douban/assets/7876607/6af57d29-c7cc-467b-bf84-4b1f702a6796">

2. obisidian版本
1.6.5

**Comment by Wanxp** [comment]
在插件中登录后操作呢

**Comment by lCanx** [comment]
你好，我也遇到了同样的问题。
![obsidan-douban](https://github.com/Wanxp/obsidian-douban/assets/68941711/e5bbbc3a-a169-4545-a29c-43fc148d869c)
版本是v1.6.5
在插件登录后依旧存在该问题。

**Comment by Wanxp** [comment]
插件重新安装也没用吗

**Comment by sayayuka** [comment]
1. 搜索的内容只要是中文字符串就会有这个问题，英文字符串没问题
2. 插件版本 2.0.5、macOS Sonoma 14.5
3. 插件重新安装，重新登录问题依旧

**Comment by deep1nlife** [comment]
临时解决方法：
1. 手动对含有中文的字符串进行URL编码
2. 对转换后的结果进行搜索

例如：「简爱」转换后为「%E7%AE%80%E7%88%B1」，将这一串字符粘贴进搜索框直接搜索即可。
在线 URL 编码 [链接1](http://www.urlencode.com.cn/)、[链接2](https://www.urlencoder.org/zh/)，还有很多同类网站选择顺手的即可。

**Comment by Wanxp** [comment]
目前手上没有mac系统，windows、linux都能正常工作， obsidian版本 1.6.5， 插件版本为2.0.5

**Comment by Wanxp** [comment]
你们都是mac系统出错吗，如果是的话我专门为mac系统做一次优化

**Comment by Wanxp** [comment]
> 临时解决方法：
> 
> 1. 手动对含有中文的字符串进行URL编码
> 2. 对转换后的结果进行搜索
> 
> 例如：「简爱」转换后为「%E7%AE%80%E7%88%B1」，将这一串字符粘贴进搜索框直接搜索即可。 在线 URL 编码 [链接1](http://www.urlencode.com.cn/)、[链接2](https://www.urlencoder.org/zh/)，还有很多同类网站选择顺手的即可。


你们都是mac系统出错吗，如果是的话我专门为mac系统做一次优化，搜索之前转为URL编码

**Comment by Wanxp** [comment]
可以尝试升级为2.0.6版本，专门为Mac系统做了搜索前的URL编码功能

**Comment by deep1nlife** [comment]
抱歉在之前的回复中没有表述清楚，我的系统是 win10 21H2，obsidian 版本号 1.6.5。
在最新的 2.0.6 版本中，我的问题已经得到了解决（跳过平台检测代码后）。既然已经错过了更新又暂时没有更多相同系统的案例，我想就不必再推送一次了。
感谢您的插件与开发工作。

**Comment by lCanx** [comment]
你好，我的系统是 win11 23H2 22631.3880
obsidian版本 v1.6.5
插件版本 2.0.6
搜索中文字符就会出现这个问题

**Comment by Wanxp** [comment]
> 抱歉在之前的回复中没有表述清楚，我的系统是 win10 21H2，obsidian 版本号 1.6.5。 在最新的 2.0.6 版本中，我的问题已经得到了解决（跳过平台检测代码后）。既然已经错过了更新又暂时没有更多相同系统的案例，我想就不必再推送一次了。 感谢您的插件与开发工作。

你是windows系统，插件版本 更新到2.0.6版本就没问题了吗？我的修改只针对Mac系统，按理不影响windows系统的，如果之前有问题，那升级到2.0.6版本应该还是有问题的

**Comment by Wanxp** [comment]
尝试了下，居然还是Obsidian版本问题：
Obsidian版本1，
Current Version: 1.6.5
Installer Version: 1.4.14 没有问题

Obsidian版本2，
Current Version: 1.6.5
Installer Version: 1.6.5 就有问题

插件2.0.7版本都加上了搜索字符的URL Encode了，感谢 @deep1nlife 提供的思路

**Comment by lCanx** [comment]
更新到2.0.7后恢复正常使用了。
感谢开发与维护！

**Comment by sayayuka** [comment]
macOS更新到2.0.7后恢复正常使用了。
感谢开发与维护！
