### ISSUE TITLE
[Bug]:请问要怎么解决ERR_UNESCAPED_CHARACTERS的问题？

### ISSUE THREAD

**Issue by Kitkatoolong** [Wanxp/obsidian-douban#119]
1. 问题说明
尝试搜索之后会弹出这样的提示话语
![image](https://github.com/Wanxp/obsidian-douban/assets/174731684/3aaefb3c-d7de-46bf-8936-7c7a8a9a014b)

**Comment by Wanxp** [comment]
是mac系统吗

**Comment by Kitkatoolong** [comment]
你好，是windows 10 22H2

**Comment by Kitkatoolong** [comment]
更新最新版本之后已可以正常运行！
