### ISSUE TITLE
书籍搜索不到

### ISSUE THREAD

**Issue by StrollStars** [Wanxp/obsidian-douban#12]
《用地图看懂世界格局》
https://book.douban.com/subject/26968875/

建议支持doubanId搜索，以便精准定位。

**Comment by Wanxp** [comment]
尝试升级到最新版本, 看是否能搜索到, 我这边是可以搜索到的: https://book.douban.com/subject/26968875/
关于使用ID直接导入的建议. 这个建议感觉可以采纳, 感谢.

**Comment by StrollStars** [comment]
可以搜索到了，谢谢。
