### ISSUE TITLE
[Bug]: 扫描微信交流群二维码一直显示“请稍后重试”

### ISSUE THREAD

**Issue by fuhan666** [Wanxp/obsidian-douban#120]
#### 1.1 操作:
扫描README.md中的微信交流群二维码

#### 1.2 结果:
```text
一直显示“请稍后重试”
```
<img src="https://github.com/user-attachments/assets/dcb525a3-aa6d-4a5b-9b52-7e9ea9089458"  width="300px"/>

### 2. 操作系统版本
- [ ] windows
- [ ] ubuntu
- [ ] mac
- [ ] android
- [x] ios

**Comment by Wanxp** [comment]
已修复
