### ISSUE TITLE
希望能增加同步看过的电影和书籍

### ISSUE THREAD

**Issue by LarryKHite** [Wanxp/obsidian-douban#13]
希望能增加同步看过的电影和书籍，要是能增加就太完美了，谢谢！

**Comment by Wanxp** [comment]
哈哈,这个在未来的计划当中. 具体如何引导导入的步骤还在考虑. 
未来的初步设想是 有个指定的文件夹,里面是同步日记或看过的电影或书籍以及其他相关信息, 以时间作为文件名(同时也是去重的依据). 可以指定时间段进行同步.
还有考虑过结合timeline插件的展示方式, 展示过去的时间线.
如果你有其他想法欢迎提出.

**Comment by Wanxp** [comment]
[v1.7.1](https://github.com/Wanxp/obsidian-douban/releases/tag/v1.7.3)以后的版本已经实现
