### ISSUE TITLE
能否自定义文件夹呢

### ISSUE THREAD

**Issue by TheGodOfKing** [Wanxp/obsidian-douban#14]
大佬，能否直接把搜索的名字作为笔记名，并且在设置中自定义每种笔记所放的位置，感觉这样能方便不少，能随时随地搜索并且放到指定位置，不用每次要到文件夹下面新建了。谢谢大佬❤❤❤
![image](https://user-images.githubusercontent.com/32014745/198822403-6b4afa3c-f156-4565-9054-c84ac67e4601.png)

**Comment by Wanxp** [comment]
OK, 这个方式感觉可行

**Comment by TheGodOfKing** [comment]
@Wanxp 
![A49BD1876119975242319C77EAEE8491](https://user-images.githubusercontent.com/32014745/198884614-0a5048a8-2069-4744-85be-61c428fd44c6.gif)

**Comment by Wanxp** [comment]
功能已发布,欢迎品尝 [v1.6.0](https://github.com/Wanxp/obsidian-douban/releases/tag/v1.6.0)
