### ISSUE TITLE
中文搜索和添加失败

### ISSUE THREAD

**Issue by apoinec** [Wanxp/obsidian-douban#15]
中文关键词搜索提示获取数据失败。通过isbn码倒是可以正常搜出对应书籍，但添加时同样提示失败。英文书籍和通过英文关键词搜出的译本没问题，可以正常添加。请问是什么原因？确认过搜索地址没问题，后面加中文能正常跳到结果页面

**Comment by Wanxp** [comment]
能否提供下你所搜索的关键词

**Comment by Wanxp** [comment]
未反馈搜索的具体信息
