### ISSUE TITLE
1.5.1更新跳不出选择界面

### ISSUE THREAD

**Issue by StrollStars** [Wanxp/obsidian-douban#16]
刚刚更新了最新版本，在搜索框中输入内容后，跳不出搜索结果。
是通过覆盖安装的方式更新，用1.5.0覆盖退回恢复，估计是新版的Bug。

**Comment by Wanxp** [comment]
https://github.com/Wanxp/obsidian-douban/releases/tag/v1.5.2
已经更新修复了. 这是由于 如果未进行 根据文件名搜索的话 有个对象没有初始化导致.
现在升级到v1.5.2就会正常.
谢谢反馈.

**Comment by Wanxp** [comment]
如果没有问题的话，issue就关闭了

**Comment by StrollStars** [comment]
感谢修复
