### ISSUE TITLE
书籍希望增加“出品方“字段

### ISSUE THREAD

**Issue by ouatis** [Wanxp/obsidian-douban#18]
如题，从书籍页面看，通常位于”出版社”字段下方，建议使用{{producer}}。

**Comment by Wanxp** [comment]
好的, 收到你的建议

**Comment by ouatis** [comment]
如豆瓣id是36061254的《略萨谈博尔赫斯
》，出品方为“99读书人”；
id 35478874的《清末民国人口贩卖与家庭生活》，出品方“世纪文景”；
id 36071679的《等待周末》，出品方“启真馆”。

**Comment by Wanxp** [comment]
ok, 我去提取下看看效果

**Comment by Wanxp** [comment]
书籍已经增加了出品方字段, 更新下书籍的模板即可使用, 最新版本: https://github.com/Wanxp/obsidian-douban/releases/tag/v1.6.1
