### ISSUE TITLE
能够抓取页面里面的评论信息么？

### ISSUE THREAD

**Issue by xiaoqiangch** [Wanxp/obsidian-douban#20]
或者提供一个修改思路，我们自己动手改一下代码

**Comment by Wanxp** [comment]
太过分了, 居然别人的评论都想要[手动狗头], 目前你只能基于带代码修改了.
我说下大体思路:
如果要实现你的需求, 你只需要修改这两个类型的类: 模型(后缀Subject类)和处理器(包含html解析器和模板替换器, 后缀为LoadHandler的类)
举例:书籍类型的评论添加
1. DoubanBookSubject.ts 添加 评论数组属性comments:string[]
2. DoubanBookParameter 添加模板中用到的参数常量,如{{comments}}
3. DoubanBookLoadHandler 中 parseText方法增加一行替换字符串的调用
```ts
.replaceAll(DoubanBookParameter.comments, super.handleSpecialContent(extract.comments, textMode, context))
```
4. DoubanBookLoadHandler中parseSubjectFromHtml方法增加对评论的html的解析,把解析结果赋予返回值
5. 完成 




PS 调试与运行插件的方式在代码README最后
祝你好运

**Comment by Wanxp** [comment]
如果没有问题的话，issue将会关闭
