### ISSUE TITLE
报错：无法替换用户信息变量，登录信息过期

### ISSUE THREAD

**Issue by tyf2018** [Wanxp/obsidian-douban#21]
刚刚才登录，就提示登录过期，请问是否还需要其它设置？

![image](https://user-images.githubusercontent.com/56342788/201461082-8d454f50-e933-4bfb-aa90-de6df3084e90.png)

**Comment by Wanxp** [comment]
确认下配置界面是否有登录信息
<img width="419" alt="1668235978219" src="https://user-images.githubusercontent.com/26840810/201461629-2381ddd7-aba5-4338-807c-83fc05761629.png">
, 尝试重开 Obsidian或重新登出登录

**Comment by tyf2018** [comment]
> 确认下配置界面是否有登录信息 <img alt="1668235978219" width="419" src="https://user-images.githubusercontent.com/26840810/201461629-2381ddd7-aba5-4338-807c-83fc05761629.png"> 

登录后无法显示出这个界面，但再次点击登录，会显示我的帐号信息
![image](https://user-images.githubusercontent.com/56342788/201462783-8ec4d4e9-5fda-455b-b62b-c1c29dacab4f.png)

**Comment by Wanxp** [comment]
那你这样做看是否可行, 
1. 在弹出得页面中先退出登录
2. 关闭obsidian
3. 再次打开obsidian
4. 进入插件点击登录

**Comment by tyf2018** [comment]
试了两遍，问题依旧

**Comment by Wanxp** [comment]
稍等我升级一个版本,修复下这个问题

**Comment by Wanxp** [comment]
好了, 最新版本修复了这个bug, [v1.6.3](https://github.com/Wanxp/obsidian-douban/releases/tag/v1.6.3)

**Comment by tyf2018** [comment]
> 好了, 最新版本修复了这个bug, [v1.6.3](https://github.com/Wanxp/obsidian-douban/releases/tag/v1.6.3)

升级后，退出登录——重启Ob——重新登录，问题依旧……（摊手）

**Comment by Wanxp** [comment]
还是在配置界面登录后, 在主界面导入电影信息时提示 登录信息过期? 你升级这个插件的方式是先卸载再重装吗?

**Comment by tyf2018** [comment]
> 还是在配置界面登录后, 在主界面导入电影信息时提示 登录信息过期? 你升级这个插件的方式是先卸载再重装吗?

在创建笔记的时候报错，另外也没有出现您截图的那种界面。升级是手动下载覆盖的

**Comment by Wanxp** [comment]
手动覆盖升级的那可能是配置文件导致有问题, 将插件目录下的data.json中loginCookiesContent属性值修改为为空,如下: 
<img width="229" alt="1668422390732" src="https://user-images.githubusercontent.com/26840810/201639628-4663f777-9177-4b57-955f-1789f824e970.png">

**Comment by Wanxp** [comment]
优化了下登录的检测，你可以再确认下是否还有问题， 插件最新版本（v1.7.1）

**Comment by tyf2018** [comment]
……呃，好像还是不行

**Comment by Gnblink0** [comment]
我也有这个问题
![image](https://user-images.githubusercontent.com/90372670/203525002-2b0cf36f-e699-4d0b-aea9-5f170bd799d5.png)

登录之后 弹出窗口直接跳转到我的豆瓣主页，但是插件里并未更新任何账号同步信息

**Comment by Wanxp** [comment]
打开窗口后显示的是已经登录豆瓣状态进行以下处理呢（保证插件为最新版本，为v1.7.3或以后的版本）：
1. 点击新窗口中右上角 我的账号
2. 在下拉选项中选择退出
3. 关闭新窗口
4. 关闭设置界面
5. 重新打开设置界面
6. 点击登录
7. 进行登录操作

**Comment by Gnblink0** [comment]
我看到了楼上的回复，也已经重复过 退出豆瓣登录-重启obsidian-清理cookie-重新登录 等操作多次，还是不行...

**Comment by Wanxp** [comment]
[1.7.4](https://github.com/Wanxp/obsidian-douban/releases/tag/1.7.4)版本增加了调试模式， 可在插件设置中开启。开启之后可以查看登录豆瓣的过程，方便定位问题。具体操作如下：
1. 升级插件到1.7.4（支持在Obsidian-设置-第三方插件-插件安装情况-（点击）检查更新，直接更新插件）
2. 打开obsidian的控制台（window系统快捷键为Ctrl+Shift+i）
3. 进入到Obsidian-豆瓣插件的设置界面，往下滑到最后，开启调试模式
4. 关闭插件设置
5. 再次打开插件设置进行登录操作
6. 关闭插件设置界面
7. 在Obsidian控制台选择 控制台页签，搜索`OB-Douban`, 复制（或截图）控制台的内容至当前Issue，类似以下截图
![image](https://user-images.githubusercontent.com/26840810/204079168-da3995dc-22f5-4c22-9c15-202f1a38016e.png)

**Comment by tyf2018** [comment]
![image](https://user-images.githubusercontent.com/56342788/204080630-42239321-f939-433a-a919-047dc2fe2d71.png)

**Comment by Wanxp** [comment]
看日志是，你登录之后的cookies没有获取到用户的信息。方便QQ远程吗+Q 977741432, 远程看下是什么问题

**Comment by tyf2018** [comment]
> 方便QQ远程吗+Q 977741432, 远程看下是什么问题

谢谢耐心解答，不过ob里都是隐私内容，还是算了。再次感谢

**Comment by Wanxp** [comment]
OK

**Comment by renlianfu** [comment]
![image](https://user-images.githubusercontent.com/27400703/204965527-9227daba-11fa-4c22-bf21-84447a570187.png)
已登录 还显示二维码 关闭窗口依旧未登录

**Comment by Wanxp** [comment]
[1.7.7](https://github.com/Wanxp/obsidian-douban/releases/tag/1.7.7)中对登录过程进行了优化，希望能解决这个问题，你们可以尝试更新到最新版本(1.7.7+)，再进行登录。 优化的内容主要是：
1. 点击登录后如果登录成功则清除当前登录窗体的缓存，防止缓存干扰登录/登出状态
2. 当已登录时点击登出将会直接清除当前用户登录cookie，而不再请求豆瓣了

登录功能在我的本机正常：
操作系统版本: `windows11`
obsidian安装程序版本: `v0.14.5`
obsidian当前版本: `v1.0.3`
如果还是有问题，后续可能做的一点是增加对整个登录链路的日志输出，以满足分析无法登录的原因。
PS: 如果可以，请把你无法登录的设备的操作系统以及obsidian留下，看是否是因为环境原因导致。

**Comment by renlianfu** [comment]
插件最新版本178
obsidian最新118
系统windows10 
![image](https://user-images.githubusercontent.com/27400703/208899765-b4e6e9df-f055-4e11-8a04-c5c4a4219777.png)

**Comment by add0213** [comment]
太难了，我是mac版本，也无法正常登录。插件版本1.8.0，但是基本数据盲，不会操作控制台啥的，只能期待作者的后续优化解决了

**Comment by Wanxp** [comment]
登录功能在我的第二台设备也正常：
操作系统版本: ubuntu22.04
obsidian安装程序版本: v1.0.3, Obsidian-1.0.3.AppImage
obsidian当前版本: v1.1.9

**Comment by Wanxp** [comment]
插件1.8.1版本增加了通过豆瓣Cookie登录的方式。如果正常登录无法进行，请尝试使用Cookie登录，具体登录方法，在插件设置中有说明。

**Comment by Wanxp** [comment]
已修复，请更新插件至最新版本([1.8.4+](https://github.com/Wanxp/obsidian-douban/releases))，异常原因在此处有[说明](https://github.com/Wanxp/obsidian-douban/issues/42#issuecomment-1511779693)
