### ISSUE TITLE
关于元数据字段填充“其他”的问题

### ISSUE THREAD

**Issue by StrollStars** [Wanxp/obsidian-douban#22]
当系列标签不存在或没有内容时，提取后的值为“其他”，建议和其他字段一样，没有就没有吧。

**Comment by Wanxp** [comment]
嗯, 可以的

**Comment by StrollStars** [comment]
发现其他字段也存在类似情况，建议没有就留空吧，不用特意填充“其他”，主要是想和豆瓣数据保持一致。

**Comment by Wanxp** [comment]
最新版本已经修改(v1.7.1+)

**Comment by StrollStars** [comment]
@Wanxp 辛苦开发者修改了，不过我刚刚想试一下，发生了如图的错误：
![2022-11-20_153427](https://user-images.githubusercontent.com/10942225/202891150-1dd3f98d-8c4d-4081-ba37-08923e230032.png)

**Comment by Wanxp** [comment]
是什么情况（操作）下出现的，能具体描述下吗

**Comment by StrollStars** [comment]
更新到最新版本1.7.3，没有问题了。

**Comment by Wanxp** [comment]
好的:)
