### ISSUE TITLE
关于同步个人看过的电影

### ISSUE THREAD

**Issue by StrollStars** [Wanxp/obsidian-douban#25]
①介绍页面是不是需要改下，截图中的部分已经实现？
![2022-11-22_232051](https://user-images.githubusercontent.com/10942225/203352226-9bbd6986-0baa-498b-966a-6f808b1d6c3e.png)
②笔记存放位置是否支持子目录？如果是该如何写？
③有些重复的会在过程中提示，结束之后可有地方查看？方便补缺。
④电影名如果中英文，则英文开始会提取不到。
⑤元数据部分，“又名”未能提取到，不过这部分有一定的复杂度，因为有特殊符号。
⑥元数据部分，如果有空格会自动舍去？
⑦同步完后，新建文件通过文件名引用豆瓣数据报错如下图，是因为访问请求次数太多了？
![2022-11-23_010226](https://user-images.githubusercontent.com/10942225/203376322-53df3f7c-0ab0-49f9-9b0f-3fc669d5a377.png)

**Comment by Wanxp** [comment]
> ①介绍页面是不是需要改下，截图中的部分已经实现

这个已经实现了，后面我再改下readme,md
> ②笔记存放位置是否支持子目录？如果是该如何写？

支持子目录的，子目录方式通过修改 配置界面的 __笔记名称__ ,支持动态参数与多级目录实现比如:
固定子目录'我的数据'则值为：`/我的数据/{{title}}` 
动态根据类型子目录，则值为：`/{{type}}/{{title}}` 
> ③有些重复的会在过程中提示，结束之后可有地方查看？方便补缺。

这个后续会有新功能， 在同步结束后新增一个文档，里面展示的是导入的状态列表
> ④电影名如果中英文，则英文开始会提取不到。

这个能否提供下名称或关键词，我去验证下
> ⑤元数据部分，“又名”未能提取到，不过这部分有一定的复杂度，因为有特殊符号。

这个能否提供下名称或关键词，我去验证下
> ⑥元数据部分，如果有空格会自动舍去？

这个没明白你的意思
> ⑦同步完后，新建文件通过文件名引用豆瓣数据报错如下图，是因为访问请求次数太多了？

这个我后续优化下。目前有概率会被豆瓣检测到（人机检测），虽然我使用了延长请求间隔时间（每次请求Douban在3秒-6秒），但还是有概率检测到。所以后续会加入提醒用户进行人机检测的验证码验证或提醒重置网络再重试。

**Comment by StrollStars** [comment]
生成的文件名问题：
①[86 -不存在的战区](https://movie.douban.com/subject/33392923/)得到的文件名是_86.md_

**Comment by Wanxp** [comment]
1. 你说的文件名问题，我接下来会一一解决，感谢反馈
2. 文件名的建议提取年份：搜索列表中的年份应该是发布日期/出版日期，你可以使用参数{{publishDate}}参数获取到该年份
3. 又名 我看下这个为啥没提取到，也会一并修复了
4. 问下 同步了大概多少个条目出现了不能同步的情况，我的条目是120条左右，最后结果是正常的。

**Comment by StrollStars** [comment]
@Wanxp 我的读书条目200条不到，没有触发这个问题；我的电影条目450条左右，这个触发了。不过幸运的是一次性能够提取完。

**Comment by Wanxp** [comment]
> ①空格开始提取不到：[86 -不存在的战区](https://movie.douban.com/subject/33392923/)→86.md
②字母开始提取不到：[3年A班：从现在起，大家都是人质](https://movie.douban.com/subject/30377729/)→3年.md
③开头的字母丢失：[Re：从零开始的异世界生活 第二季](https://movie.douban.com/subject/30353116/)→从零开始的异世界生活第二季.md
④空格丢失：[TARI TARI](https://movie.douban.com/subject/10554914/)→TARITARI.md
⑤提取多余字符：[东之伊甸](https://movie.douban.com/subject/3681358/)→东之伊甸東.md

> ②又名未提取：[拜托了老师](https://movie.douban.com/subject/2075971/)又名星空的邂逅

上述问题都已修复

**Comment by StrollStars** [comment]
@Wanxp 测试1.7.5，似乎空格丢失的问题还是存在，麻烦看下。
另外斜杠可否保留而不是转换成逗号，不然里面有逗号就会多产生分段，例子可见[拜托了老师](https://movie.douban.com/subject/2075971/)：
>Please, Teacher / 星空的邂逅 / Onegai, Teacher / 拜托了，老师

转换后就成了
>Please, Teacher , 星空的邂逅 , Onegai, Teacher , 拜托了，老师

如果可行的话，建议书籍也能同步修改。

**Comment by FeiLZX3Km** [comment]
亲爱的开发者，我现在通过该插件搜索豆瓣并创建任意文档内容，均会遇到与上方相同的情况……
![微信截图_20221126204956](https://user-images.githubusercontent.com/21981195/204090386-609ded7e-6fa8-434e-891e-5748fce99de8.png)

**Comment by StrollStars** [comment]
@FeiLZX3Km 短时间内请求数据太多，明天再试试，应该就可以了。

**Comment by Wanxp** [comment]
现在支持了增量同步， 后续如果出现了403，第二天再同步下应该就可以了

**Comment by StrollStars** [comment]
@Wanxp https://github.com/Wanxp/obsidian-douban/issues/25#issuecomment-1328019269 的问题麻烦看下。

**Comment by Wanxp** [comment]
> Onegai, Teacher /

嗯嗯，谢谢反馈，这里的 Onegai, Teacher 感觉使用“”包含就可以，后续会修复这个bug（即内容包含分隔符则使用双引号包含内容）， 并且现在分隔符号在配置中是可以自定义的，可以定义成你想要的任何字符，比如/

**Comment by Wanxp** [comment]
> @Wanxp 测试1.7.5，似乎空格丢失的问题还是存在，麻烦看下。 另外斜杠可否保留而不是转换成逗号，不然里面有逗号就会多产生分段，例子可见[拜托了老师](https://movie.douban.com/subject/2075971/)：
> 
> > Please, Teacher / 星空的邂逅 / Onegai, Teacher / 拜托了，老师
> 
> 转换后就成了
> 
> > Please, Teacher , 星空的邂逅 , Onegai, Teacher , 拜托了，老师
> 
> 如果可行的话，建议书籍也能同步修改。

使用斜杆作为分隔符时 obsidian frontmatter 无法识别为数组， 所以我使用了“_”代替特殊字符， aliases本质上也可以认为是文件名，其实应该要用处理文件名的方式处理这个属性是最好的。

**Comment by StrollStars** [comment]
@Wanxp 感谢开发者解释，那这个问题就这么处理吧。

**Comment by StrollStars** [comment]
> 2\. 文件名的建议提取年份：搜索列表中的年份应该是发布日期/出版日期，你可以使用参数{{publishDate}}参数获取到该年份
参数是{{datePublished}}吧？不过提取出来的是XXXX-XX-XX格式的日期，不是纯年份。
