### ISSUE TITLE
看过的书有些信息获取不到

### ISSUE THREAD

**Issue by StrollStars** [Wanxp/obsidian-douban#26]
登录了豆瓣帐号，模板也是用了含有我的相关信息的模板，但是提取后的文件缺少我的信息。
影视提取没有这个问题。
卸载后重新安装无效。

PS：复制后的粘贴菜单，直接粘贴和作为文本粘贴有什么区别？

**Comment by Wanxp** [comment]
1. 是否有在配置界面中 __电影模板__ 中选择你的电影模板文件作为模板
2. 直接粘贴是会保留格式转换成markdown的格式， 作为文本粘贴则是原始内容（推荐这个粘贴）。举个例子，你可以复制当前issue的标题，然后分别以上述两种粘贴方式粘贴在obsidian中，最后的结果是有区别的
![image](https://user-images.githubusercontent.com/26840810/203695245-d5733a3f-6262-42dd-9999-67b617f6d8b8.png)

**Comment by StrollStars** [comment]
@StrollStars 1.我复制的是左边的按钮，为了确保粘贴无误，我还特意把粘贴后的内容复制粘贴出来，确认含有带有my的部分。会不会是插件无法识别我已经登录了，所以获取到的只是基础模板的信息？
PS：如果成功的话，我的短评应该也能带出来对吧？
2.谢谢，那我就用文本粘贴了。

**Comment by StrollStars** [comment]
程序和仓库全部删除重来，登录显示：
> error code: 004

**Comment by Wanxp** [comment]
> 程序和仓库全部删除重来，还是提取不出来，是不是没救了……
不配置模板的情况下会使用默认模板，如果登录了就会使用带有你的评论的模板，这个时候呢，还是没办法提取吗

**Comment by StrollStars** [comment]
@StrollStars 对，我怎么都提取不出读书中我的信息来，有别人反映同类问题吗？

**Comment by Wanxp** [comment]
> @Wanxp 对，我怎么都提取不出读书中我的信息来，有别人反映同类问题吗？ 其实我有点儿怀疑代码，读书的代码和电影的代码是同一段么？

确实书籍类的个人信息没有正常导入，这个我来修复下

**Comment by Wanxp** [comment]
发布的1.7.4版本修复上述所有问题。
现在支持在Obsidian-设置-第三方插件-插件安装情况-（点击）检查更新，直接更新插件了

**Comment by Wanxp** [comment]
[1.7.4](https://github.com/Wanxp/obsidian-douban/releases/tag/1.7.4)版本增加了调试模式， 可在插件设置中开启。开启之后可以查看登录豆瓣的过程，方便定位问题。具体操作如下：
1. 升级插件到1.7.4（支持在Obsidian-设置-第三方插件-插件安装情况-（点击）检查更新，直接更新插件）
2. 打开obsidian的控制台（window系统快捷键为Ctrl+Shift+i）
3. 进入到Obsidian-豆瓣插件的设置界面，往下滑到最后，开启调试模式
4. 关闭插件设置
5. 再次打开插件设置进行登录操作
6. 关闭插件设置界面
7. 在Obsidian控制台选择 控制台页签，搜索`OB-Douban`, 复制（或截图）控制台的内容至当前Issue，类似以下截图
![image](https://user-images.githubusercontent.com/26840810/204079168-da3995dc-22f5-4c22-9c15-202f1a38016e.png)

**Comment by StrollStars** [comment]
@Wanxp 感谢更新，不过我发现了新的问题：自定义模板无效，也就是说我调整模板内容顺序比如目录在我的短评之前，没有效果。
看到官网插件能搜到了，不过如果想通过程序更新，得解决网络问题。

**Comment by Wanxp** [comment]
刚试过音乐/电影/书籍的自定义模板是有效果的，不知道你是怎么操作不能调整的

**Comment by StrollStars** [comment]
@Wanxp 我现在出问题的地方是在同步我的书籍
①同步设置中的模板和模板配置中的模板，两边是不是独立的？我觉得两边能够保持一致比较好，或者说存取在同一位置。
②我是想把目录提到短评前面，然后从模板设置中的内容复制到同步设置里后进行同步，得到的结果还是短评在目录前面。
③`Comment`两字修改成`短评`无效，目录前新增`Menu`或`目录`也无效。

**Comment by Wanxp** [comment]
> ①同步设置中的模板和模板配置中的模板，两边是不是独立的？我觉得两边能够保持一致比较好，或者说存取在同一位置。

同步设置第一次打开时取的是插件配置的设置，修改同步设置不会影响插件配置中的设置，相当于同步设置中的设置只是临时配置

> ②我是想把目录提到短评前面，然后从模板设置中的内容复制到同步设置里后进行同步，得到的结果还是短评在目录前面。

这个最新版修复了，你可以确认下

>③Comment两字修改成短评无效，目录前新增Menu或目录也无效。

这个最新版本也试过已经好了，你看下现在还有这个问题不。

**Comment by StrollStars** [comment]
@Wanxp 我以覆盖替换文件的方式更新，发现②和③的问题依旧，需要全部删除全新更新吗？

**Comment by Wanxp** [comment]
> @Wanxp 我以覆盖替换文件的方式更新，发现②和③的问题依旧，需要全部删除全新更新吗？

有操作视频吗，我看下什么情况下会出现，我这里试过几次没有出现你说的情况

**Comment by StrollStars** [comment]
先复制模板
---
```
---
doubanId: {{id}}
title: {{title}}
subTitle: {{subTitle}}
originalTitle: {{originalTitle}}
series: {{series}}
type: {{type}}
author: {{author}}
score: {{score}}
myRating: {{myRating}}
datePublished: {{datePublished}}
translator: {{translator}}
publisher: {{publisher}}
producer: {{producer}}
isbn: {{isbn}}
url: {{url}}
totalPage: {{totalPage}}
price: {{price}}
tags: Book, {{myTags}}
state: {{myState}}
binding: {{binding}}
createTime: {{currentDate}} {{currentTime}}
collectionDate: {{myCollectionDate}}
desc: {{desc}}
---

![image|150]({{image}})

Comment: 
---
{{myComment}}

{{menu}}

```
再粘贴到文本编辑器中调整目录位置
------
```
doubanId: {{id}}
title: {{title}}
subTitle: {{subTitle}}
originalTitle: {{originalTitle}}
series: {{series}}
type: {{type}}
author: {{author}}
score: {{score}}
myRating: {{myRating}}
datePublished: {{datePublished}}
translator: {{translator}}
publisher: {{publisher}}
producer: {{producer}}
isbn: {{isbn}}
url: {{url}}
totalPage: {{totalPage}}
price: {{price}}
tags: Book, {{myTags}}
state: {{myState}}
binding: {{binding}}
createTime: {{currentDate}} {{currentTime}}
collectionDate: {{myCollectionDate}}
desc: {{desc}}
---

![image|150]({{image}})

{{menu}}

Comment: 
---
{{myComment}}

```
最后将调整后的代码复制粘贴到复制模板左边的框中（有个放大镜那个）
---

**Comment by Wanxp** [comment]
放大镜的那个输入框是选择模板文档的选择框，不是模板内容录入框哦。

**Comment by StrollStars** [comment]
@Wanxp 就是说我要单独为模板写个文件，然后在框里选择？

**Comment by Wanxp** [comment]
> 1. 已同步的信息保存在data.json文件中，但是如果文件被删除依旧会视为已同步。

文件被删除需要在同步设置中关闭增量更新即可更新下来。 根据文件名过滤不好处理，因为现在文件名也是可以由用户自己定义的。原也想过使用豆瓣ID，但不一定每一个人都会在文件中使用豆瓣ID，所以折中的方式在同步时记录下来已经同步的ID，做内部的筛选

**Comment by StrollStars** [comment]
> 所以折中的方式在同步时记录下来已经同步的ID，做内部的筛选
但是这样就出现了我所说的问题，如果关掉增量更新就是同名处理的问题了。
或者把增量更新替换为同名文件的处理方式如何呢？跳过或覆盖。

**Comment by Wanxp** [comment]
> > 所以折中的方式在同步时记录下来已经同步的ID，做内部的筛选
> 
> 但是这样就出现了我所说的问题，如果关掉增量更新就是同名处理的问题了。 或者把增量更新替换为同名文件的处理方式如何呢？跳过或覆盖。

对的，关掉增量更新，就是同名处理的过滤了。其实不关掉增量增量更新， 新增的部分同名覆盖处理也可能会影响。
这两个选项的目的是不同的：
__增量更新__ 的目的是 _减少同步时间_，根据以前的记录剔除掉将要同步列表中大量已拉取的数据。
__同名覆盖__ 的目的是让用户选择是否要保留之前的文档内容，_防止用户自己编辑的条目内容被覆盖丢失_ 。
同名覆盖是已经把电影对象获取到了，这时候根据文件名称模板生成文件名，再去写入，写入过程中检测是否已经存在文档，其实这个时候该耗费的时间已经耗费了（是否增量已无意义）

**Comment by StrollStars** [comment]
@Wanxp 看来是不好处理各种场景，那就先保留原状吧，此贴作结。
