### ISSUE TITLE
无法搜素或者添加书籍，错误403

### ISSUE THREAD

**Issue by Anpoe** [Wanxp/obsidian-douban#28]
![image](https://user-images.githubusercontent.com/25424504/204667174-84ac9d58-9fd6-449c-842b-ef1c196ba964.png)

换过仓库试过，重启，卸载也试过，豆瓣的网站能顺利打开，似乎不是网页的问题？
也没有更改过设置，用的默认数据。

---
打开调试模式看了一下
![image](https://user-images.githubusercontent.com/25424504/204668491-c1b67fff-004e-40aa-b26e-6f47e48f3a3b.png)

**Comment by Wanxp** [comment]
可能和数据同步数量较多触发了豆瓣的 防爬机制，第二天是不是也能导入一部分之后出现403
未来暂时优化的方向是：
1. 对于200条后的数据进行更加长时间的等待，即超过200条的部分每次请求时间增加到10-15秒（时间待定）
2. 支持出现错误后的增量同步(类似断点续传)

**Comment by Anpoe** [comment]
谢谢回复，今天再试的时候问题已经解决了
