### ISSUE TITLE
书籍信息提取部分元数据错误

### ISSUE THREAD

**Issue by StrollStars** [Wanxp/obsidian-douban#30]
《[禁忌魔术](https://book.douban.com/subject/25756926/)》：描述部分自带半角引号，因而取出后开头有两个半角引号。
《[深入解析Windows操作系统](https://book.douban.com/subject/2031396/)》：把添加的引号剔除就行了。

**Comment by Wanxp** [comment]
好的， 最新版本[1.7.8](https://github.com/Wanxp/obsidian-douban/releases/tag/1.7.8)已修复上述问题了

**Comment by StrollStars** [comment]
@Wanxp 速度好快，感谢开发者。
