### ISSUE TITLE
获取中文和英文名字时，英文名和姓之间无空格

### ISSUE THREAD

**Issue by TtlyLynzie** [Wanxp/obsidian-douban#31]
如图：
<img width="596" alt="CleanShot 2022-12-04 at 09 28 49@2x" src="https://user-images.githubusercontent.com/62136973/205469627-2ab91cc7-1f4a-47b1-b0ea-51653fca0001.png">

HunterSchafer → Hunter Schafer

**Comment by Wanxp** [comment]
1.9.7 版本修复该问题
