### ISSUE TITLE
关于魔劣的搜索问题

### ISSUE THREAD

**Issue by StrollStars** [Wanxp/obsidian-douban#32]
书籍：
[魔法科高中的劣等生 01](https://book.douban.com/subject/10483485/)
问题：
1. 直接搜索搜不到这本书
2. 用豆瓣ID搜索为空
3. 用ISBN搜索404错误

**Comment by StrollStars** [comment]
@Wanxp 它的搜索结果是由什么确定的，我刚刚试了下，先新建文档和先搜索，得到的结果都是只有一个电视剧和四个日记，一个书的结果都没了。

**Comment by Wanxp** [comment]
> 先新建文档和先搜索（关键词“魔法科高中的劣等生”），得到的结果都是只有一个电视剧和四个日记，一个书的结果都没了。

这种方式我尝试过，是有一本书和三条日记的

**Comment by Wanxp** [comment]
最新版本支持搜索翻页，搜索关键词后 [魔法科高中的劣等生 01](https://book.douban.com/subject/10483485/) 往下翻页可以得到你要的结果，

**Comment by StrollStars** [comment]
@Wanxp 感谢更新，确实能够搜到了，现在有两个问题：
1. 可否支持不登录翻页
2. 登录可否持久

不然要时不时登录，感觉不太方便。

**Comment by Wanxp** [comment]
1. 可否支持不登录翻页或一页显示尽可能长
 这个时豆瓣的网页限制，要获取第二页必须要登陆才行

2. 登录持久
这个登录时间我可以尝试优化下，登录后，每次请求豆瓣动态跟新Cookie保证登录状态的延续。

3. 出版社和定价
这个没有的话能否给出isbn或豆瓣ID

**Comment by StrollStars** [comment]
关于3，还是这本书：[魔法科高中的劣等生 01](https://book.douban.com/subject/10483485/)

**Comment by StrollStars** [comment]
The issue has been resolved.
