### ISSUE TITLE
示例图片如何实现的？

### ISSUE THREAD

**Issue by StrollStars** [Wanxp/obsidian-douban#34]
<img width="992" alt="background" src="https://user-images.githubusercontent.com/10942225/206828985-7669975c-3b99-41d8-9b51-c2576b3c428c.png">
这个图片的效果是如何实现的？就是书影音的信息能够在阅览模式展示出来，还是说信息没放在元数据区？

**Comment by Wanxp** [comment]
图面没放在元数据区域即可，如下：
---
元数据区域
---

`![图片名称|图片宽度](图片地址)`
`![肖申克的救赎|200](/asserts/xxxx.png)`

**Comment by StrollStars** [comment]
@Wanxp 我没说清，我的图片指的是整张图片，不是笔记插入的图片。
我的本意是想问，怎么让元数据以图片中的样子展示出来？

**Comment by Wanxp** [comment]
使用metatable插件即可有这个效果

**Comment by StrollStars** [comment]
@Wanxp 这个插件太棒了，感谢分享。
