### ISSUE TITLE
关于附件位置的建议

### ISSUE THREAD

**Issue by StrollStars** [Wanxp/obsidian-douban#35]
现状
---
当程序/库的附件默认存放路径为`当前文件所在文件夹下指定的子文件夹中`，而电影和读书又分开文件夹时，无法把文章对应的图片放入其同级的附件子目录，由于附件的父文件夹命名任意，所以也没办法用变量替代。

举例
---
`电影`和`图书`为两个目录，其下分别有个名为`附件`的子文件夹专门用于对应的附件，目前想要的是`电影A.md`的附件放在`电影\附件`文件夹下，`图书B.md`的附件放在`图书\附件`文件夹中。目前插件只能指定附件放在两个附件文件夹中的其中一个，由于`电影`和`图书`两个目录命名不一定匹配变量，所以也无法用`变量\附件`的方式指定附件目录。

建议
---
可否当附件存放位置为空时，附件存放位置跟随程序/库而定？

**Comment by Wanxp** [comment]
我的建议是图片作为附件，非文本内容（非我们的笔记内容）最好统一存放，否则散落到笔记文件夹中，会比较混乱

**Comment by StrollStars** [comment]
@Wanxp 我目前的结构如下图所示，所以希望插件能给个选项，跟随库设置。
![2022-12-15_001204](https://user-images.githubusercontent.com/10942225/207648952-b7b89342-4bf6-413a-b4ad-120d35cec472.png)

**Comment by Wanxp** [comment]
obsidian 的设置中指定的附件位置吗？这个功能我也想实现，但是没找到obsidian对应的api。（如果你知道欢迎补充）
PS 你这张图截取的是哪个插件的。

**Comment by StrollStars** [comment]
@Wanxp 最近发现[Local Images Plus](https://github.com/Sergei-Korneev/obsidian-local-images-plus)有如下设置，或许可以参考：
![2023-02-05_174928](https://user-images.githubusercontent.com/10942225/216812194-1666405a-9f0f-4406-a53d-cc0923f08974.png)

**Comment by Wanxp** [comment]
> @Wanxp 最近发现[Local Images Plus](https://github.com/Sergei-Korneev/obsidian-local-images-plus)插件有如下设置，或许可以参考：
> ![2023-02-05_174928](https://user-images.githubusercontent.com/10942225/216812194-1666405a-9f0f-4406-a53d-cc0923f08974.png)

OK，回头我研究研究，感谢

**Comment by StrollStars** [comment]
@Wanxp 开发者可有时间解决下吗？

**Comment by Wanxp** [comment]
因为这个功能不太影响整体功能，所以没有作为重点功能去紧急开发，我这两周估计会抽空弄下

**Comment by StrollStars** [comment]
@Wanxp 谢谢，麻烦开发者了。

**Comment by hipedo** [comment]
同求这个功能，谢谢提问者和开发者

**Comment by ruinshe** [comment]
可以试试最新版，附件的位置设置成 `{{myType}}/附件`，当然可以加自己的前缀（有必要的话）。
