### ISSUE TITLE
文件名显示发行年份

### ISSUE THREAD

**Issue by bpking1** [Wanxp/obsidian-douban#36]
请问支持配置在文件名中显示年份吗，比如: 西游记 (2003) ，有时候碰到不同影视名字相同的情况会有冲突

**Comment by Wanxp** [comment]
支持的，建议插件中文件名配置成: `{{type}}/{{title}}({{publishDate}})`

**Comment by bpking1** [comment]
好的,谢谢答复

**Comment by Wanxp** [comment]
最新版本(1.7.9+)增加了yearPublished参数（出版年份、发行年份, 如2008，具体见README参数说明），可以使用如下模板
`{{type}}/{{title}}({{yearPublished}})`
获取到如下效果：
`电视剧/西游记(2003)`

**Comment by Wanxp** [comment]
如果没问题的话，这个issues将会在24小时后关闭

**Comment by bpking1** [comment]
谢谢更新，只保留年份会简洁一点，那我把issue关了
