### ISSUE TITLE
建议增加电影年份字段

### ISSUE THREAD

**Issue by robertzml** [Wanxp/obsidian-douban#38]
建议增加电影年份字段: year
方便文件命名或者分类。

谢谢！

**Comment by StrollStars** [comment]
https://github.com/Wanxp/obsidian-douban/issues/25#issuecomment-1327012752
第二点，不过作者给的参数写错了，应该是`datePublished`。

**Comment by robertzml** [comment]
> [#25 (comment)](https://github.com/Wanxp/obsidian-douban/issues/25#issuecomment-1327012752) 第二点，不过作者给的参数写错了，应该是`datePublished`。

`datePublished` 是年月日，有办法可以格式化吗？

**Comment by StrollStars** [comment]
@robertzml 插件本身可能没有办法，可以用第三方批量重命名软件。

**Comment by Wanxp** [comment]
最新版本(1.7.9+)增加了yearPublished参数（出版年份、发行年份, 如2008，具体见README参数说明），所有类型的条目都都支持此参数，可以用于文件名.

**Comment by StrollStars** [comment]
@Wanxp 嗯，看到了，早知道你会更新我就等你了，几百个我手动改完了。😂

**Comment by Wanxp** [comment]
如果没问题的话，这个issues将会在24小时后关闭
