### ISSUE TITLE
登陆后无效

### ISSUE THREAD

**Issue by milla** [Wanxp/obsidian-douban#42]
![Uploading image.png…]()
依然显示"Login"

**Comment by Preston2jager** [comment]
遇到类似问题，我一个新账号可以登录，朋友的老账号无法登录，怀疑跟注册手机号不是国内号有关

**Comment by Wanxp** [comment]
插件1.8.1版本增加了通过豆瓣Cookie登录的方式。如果正常登录无法进行，请尝试使用Cookie登录，具体登录方法，在插件设置中有说明。

**Comment by yan9qu** [comment]
> 插件1.8.1版本增加了通过豆瓣Cookie登录的方式。如果正常登录无法进行，请尝试使用Cookie登录，具体登录方法，在插件设置中有说明。

还不是不行啊 老大，两种登录方法都不太好使

**Comment by Wanxp** [comment]
> 遇到类似问题，我一个新账号可以登录，朋友的老账号无法登录，怀疑跟注册手机号不是国内号有关

是否如 @Preston2jager 提到的是国外手机号码。

**Comment by yan9qu** [comment]
国内联通的

Sent with Spark
2023年4月17日 +0800 23:40 wanxp ***@***.***>，写道：

**Comment by yan9qu** [comment]
哇 谢谢谢谢 我现在发，感谢

Sent with Spark
2023年4月17日 +0800 23:44 wanxp ***@***.***>，写道：

**Comment by Wanxp** [comment]
> 哇 谢谢谢谢 我现在发，感谢 Sent with Spark 2023年4月17日 +0800 23:44 wanxp ***@***.***>，写道：
> […](#)
> 由于我这边访问是正常的，包括账号登录方式、Cookie方式以及测试了Ubuntu、Windows系统都是正常登录。 ***@***.***， 协助解决无法登录问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>


已经修复， 异常原因如下：
在插件中登录时，之前我这边处理一直以为豆瓣的用户ID是全数字，解析时按照全数字处理。但是事实上有的豆瓣逻辑ID是拼音或包含字母，则解析会失败出现异常，导致登录失败。这就是为什么有的人能登录成功有的登录失败。现在登录功能都已正常。
若还有问题欢迎继续反馈。

感谢 @yan9qu 的协助

**Comment by yan9qu** [comment]
酷！谢谢
