### ISSUE TITLE
似乎不支持英文书籍

### ISSUE THREAD

**Issue by milla** [Wanxp/obsidian-douban#45]
搜索"solution architect"
结果：
<img width="894" alt="image" src="https://user-images.githubusercontent.com/297531/215119638-81ed4262-5e40-4b02-97b8-a107ca79be45.png">

https://search.douban.com/book/subject_search?search_text=solution+architect&cat=1001
实际茫茫多。。。

**Comment by Wanxp** [comment]
还真是， 看了下是豆瓣主页上搜索,地址https://www.douban.com/（非选中书籍类型搜索,地址https://book.douban.com/）时会只出现一个结果。这种情况未来可以优化下，比如增加分号，指定类型搜索关键词如：“书籍:solution architect”

**Comment by milla** [comment]
> https://search.douban.com/book/subject_search?search_text=solution+architect&cat=1001

又看了下，douban用的是模糊查询... solution architect，结果是 solutions + solution + architect, 所以会多...

**Comment by Wanxp** [comment]
现在最新版本在搜索页面增加了下一页功能，可以看到之前没有看到的内容
