### ISSUE TITLE
Bug: ISBN搜索无法添加文件

### ISSUE THREAD

**Issue by milla** [Wanxp/obsidian-douban#46]
实例：
输入 9781838645649
有搜索结果
<img width="971" alt="image" src="https://user-images.githubusercontent.com/297531/215119903-8887caae-5fe8-4d9b-b518-0c657e64eb23.png">
选中后，出现错误：
<img width="453" alt="image" src="https://user-images.githubusercontent.com/297531/215120023-499dbab8-96fc-483d-8a56-c9bf736d7a1e.png">

**Comment by milla** [comment]
部分书无法检索到
恐惧和战栗 https://book.douban.com/subject/1020296/

**Comment by Wanxp** [comment]
https://github.com/Wanxp/obsidian-douban/releases/tag/1.8.2
以上bug已修复
1. 输入 9781838645649 后检索到并选择报错
2. 恐惧和战栗 无法检索
