### ISSUE TITLE
cookie 登录失败

### ISSUE THREAD

**Issue by thewangcj** [Wanxp/obsidian-douban#48]
根据教程获取 cookie 后登录失败，下面是 debug 信息
![image](https://user-images.githubusercontent.com/13983218/222697737-64a07a5f-91ce-4b9a-ac61-336102b32958.png)

直接登录也失败
![image](https://user-images.githubusercontent.com/13983218/222697857-f1a8153c-05c7-4a21-926f-81d20d0a9ecf.png)

看报错都是通过 cookie 获取用户信息失败

**Comment by Wanxp** [comment]
是不是你复制的cookie有问题，能否截图并马赛克处理后贴上来看下

**Comment by thewangcj** [comment]
我换了个号用 cookie 登录上了，下面是两个 cookie 的截图，下面的可以登录，上面的不行

![4796b8269dd40e7c4e7d8c08764212c](https://user-images.githubusercontent.com/13983218/225549460-6fe69103-67dd-4961-941f-a6ed089d8495.jpg)

**Comment by Wanxp** [comment]
已修复，请更新插件至最新版本([1.8.4+](https://github.com/Wanxp/obsidian-douban/releases))，异常原因在此处有[说明](https://github.com/Wanxp/obsidian-douban/issues/42#issuecomment-1511779693)

**Comment by thewangcj** [comment]
更新后登录成功了，Thanks♪(･ω･)ﾉ
