### ISSUE TITLE
阅读模式只显示图片

### ISSUE THREAD

**Issue by ruyan427** [Wanxp/obsidian-douban#52]
你好，想问一下阅读模式只显示图片，模板点开阅读模式有这个错误是怎么回事。
![image](https://user-images.githubusercontent.com/127956220/228520141-4746cf72-45c7-449c-9f75-0f356888b5db.png)

**Comment by Wanxp** [comment]
这是模板，用编辑模式查看即可

**Comment by ruyan427** [comment]
感谢回复，
![image](https://user-images.githubusercontent.com/127956220/229001983-2e17d6fe-a76c-432f-b0af-7244a763c9c5.png)
但是导入之后点阅读模式上面内容就消失了T.T

**Comment by ruyan427** [comment]
可以了，非常感谢
