### ISSUE TITLE
Cookie登录失败

### ISSUE THREAD

**Issue by Xie-Zhixuan** [Wanxp/obsidian-douban#53]
尝试直接用户登录,在弹窗中显示登录成功但退出弹窗后,并没有在配置页面显示相关用户信息.
随后使用cookie登录,但依然报错.

**Comment by ghostzhang** [comment]
+1

**Comment by Xie-Zhixuan** [comment]
该问题已解决,但出现新问题
下载的图片后缀格式的"."被替换为"_"导致不能正常显示图片,翻阅了一下代码发现是自动替换了文件名的".jpg"的"."
FileUtil.parse()方法中的fileName.replaceAll(/[\\/:*?"<>|.]/g, "_");
我把通配符里的"."去掉以后问题得到解决
