### ISSUE TITLE
是否可以增加一个字段去显示高清大图的网址

### ISSUE THREAD

**Issue by TheGodOfKing** [Wanxp/obsidian-douban#54]
**大佬能增加一个字段去显示高清大图的网址么，如{{himage}},因为我想要这个高清大图的网址，但是又想下载图片，在插件中开启下载高清大图功能后，链接就被替换了，所以想要个字段去显示高清大图的网址，并且现在默认的封面也是不高清的，需要下载才会显示高清大图，所以希望大佬能优化下，感谢🙏🙏🙏🙏🙏🙏**
![G1W{HN7% FA6HSE63$KTX7T](https://user-images.githubusercontent.com/32014745/230542344-f752346b-fc4e-4cc3-a5e7-f819d646bdba.gif)

**Comment by Wanxp** [comment]
配置中有个是否保存高清图片的选项，这个可以吗

**Comment by TheGodOfKing** [comment]
@Wanxp 
![image](https://user-images.githubusercontent.com/32014745/231824209-32aaaa8c-1da8-46ad-a8a3-b2db43d67d95.png)
不开这个默认不是高清大图

**Comment by Wanxp** [comment]
1.8.9版本增加了低清晰度的url

**Comment by Wanxp** [comment]
高清图片的网址 是需要登录豆瓣才能获取的，这就意味着，不用作为普通的地址访问，如果要使用高清的封面，请勾选设置中的保存高清封面功能
