### ISSUE TITLE
书名含有非法字符导致创建失败

### ISSUE THREAD

**Issue by LiuOcean** [Wanxp/obsidian-douban#55]
如一些书名含有 "." 关键字，或者 ":" 关键字时，创建文件会被 Obsidian 拦截。可以使用 「.Net内存管理宝典」作为书名测试。

希望提供一个非法字符的 replace 配置，比如此处的 "." 可以替换为 "-" 或者 "_"

**Comment by Wanxp** [comment]
1.9.9版本已修复
