### ISSUE TITLE
同步时显示0/0

### ISSUE THREAD

**Issue by Yami0425** [Wanxp/obsidian-douban#58]
我是第一次使用，登陆显示成功，但是同步的时候一直是0/0，同步成功，这种情况应该怎么办？
![image](https://github.com/Wanxp/obsidian-douban/assets/44643204/df01d5ef-0b11-4c3a-bf77-a0aaa3485719)

**Comment by V1stone** [comment]
我也遇到同样的情况。补充一点，登录成功但昵称为：登录豆瓣。用cookie登录但始终不成功。
![image](https://github.com/Wanxp/obsidian-douban/assets/103471916/50086764-1008-43bf-a441-87567733bf91)

**Comment by Yami0425** [comment]
> 我也遇到同样的情况。补充一点，登录成功但昵称为：登录豆瓣。用cookie登录但始终不成功。 ![image](https://user-images.githubusercontent.com/103471916/240099481-50086764-1008-43bf-a441-87567733bf91.png)

我的昵称也是登陆豆瓣，cookie也不能成功

**Comment by Wanxp** [comment]
应该是没登录成功。
1. 现在的截图是，很久前已经登录，现在打开看到的情况吗
2. 登出 再重新登录有效果吗
3. 豆瓣昵称是什么（这个有可能是豆瓣昵称有字符没识别到，所以需要了解昵称是什么）
4. 上述无法解决，如果可以请将你用于登录的Cookie发送至邮箱977741432@qq.com，我来本地调试验证下

**Comment by Wanxp** [comment]
@Yami0425 已在邮箱中收到你的信息，正在处理此BUG感谢反馈。

**Comment by Wanxp** [comment]
> > 我也遇到同样的情况。补充一点，登录成功但昵称为：登录豆瓣。用cookie登录但始终不成功。 ![image](https://user-images.githubusercontent.com/103471916/240099481-50086764-1008-43bf-a441-87567733bf91.png)
> 
> 我的昵称也是登陆豆瓣，cookie也不能成功

能否帮忙通过邮箱重新发一下Cookie

**Comment by Yami0425** [comment]
> 

已经发送，辛苦查收！

**Comment by V1stone** [comment]
> 以上已修复

还是无法登陆

**Comment by Wanxp** [comment]
已修复登录问题
