### ISSUE TITLE
始终无法登录

### ISSUE THREAD

**Issue by los-sun** [Wanxp/obsidian-douban#68]
用插件内的登录，弹出的网页登录后没有反应
cookies登录，一直提示无法登录

**Comment by SYYDSN** [comment]
me too

**Comment by h-ruii** [comment]
+1

**Comment by lisasuosuo** [comment]
+1

**Comment by yaomumu** [comment]
+1

**Comment by lCanx** [comment]
+1，两种方式都不行

**Comment by StrollStars** [comment]
同样两种方式都不行，不知道是不是和帐号有关。

**Comment by Estherbad** [comment]
确实无法登录，很尴尬

**Comment by Gnblink0** [comment]
+1 莫非是我的豆瓣名字里有日语片假名😹 用了cookies也不行
![image](https://github.com/Wanxp/obsidian-douban/assets/90372670/65071146-fb02-4960-bbe8-c4dc6787e9e3)
确信自己应该没有找错cookie

**Comment by Wanxp** [comment]
插件1.9.0版本（或以上）再试下

**Comment by lisasuosuo** [comment]
亲爱的作者大大你终于回复了，升级到1.9.0还是用两种方法都无法登录，有什么数据我能提供给你？

**Comment by Wanxp** [comment]
> 亲爱的作者大大你终于回复了，升级到1.9.0还是用两种方法都无法登录，有什么数据我能提供给你？

加下QQ群：179348535，群里沟通下

**Comment by Estherbad** [comment]
ip的问题，挂梯子换其他地区Yingyi Fang在 2023年9月12日，15:30，关念 ***@***.***> 写道：﻿
+1 莫非是我的豆瓣名字里有日语片假名😹 用了cookies也不行

确信自己应该没有找错cookie

**Comment by Wanxp** [comment]
这次更新修复了，原不能登录的同学可以试下最新版本是否能登录
