### ISSUE TITLE
内容简介没法读全

### ISSUE THREAD

**Issue by joyq28** [Wanxp/obsidian-douban#71]
内容简介只能读到省略号之前的， 例如下文，不知道是不是没法登陆的原因
---
职场上，成功的人总是把失败的经验写在笔记本上，然后重新出发；追求成果的人总在积极改变工作习惯，善用笔记本“捕获”升级加薪的机会；注重自我投资的人不会让时间和金钱白白溜走，学以致用只为成就梦想。
本书告...

**Comment by Wanxp** [comment]
1.9.7 版本修复该问题

**Comment by Wanxp** [comment]
问题已修复
