### ISSUE TITLE
演员名称一般使用富文本格式，方便在Projects插件中查看整理，但是无论是通过`[[{{actor}}]]`这种方式也只能框选整体

### ISSUE THREAD

**Issue by logan00000000** [Wanxp/obsidian-douban#74]
在解决这种问题过程中发现一种方法，在使用`[[{{actor}}]]`基础上改变**数组分割字符串**为`]],[[`可以达到每个人名都有创建链接的目的。但是`{{aliases}}`创建不需要框选，所以这种使用方法仅限于不用alisaes的条件上。
为此我放弃了使用富文本格式的想法，改用`- `方式进行列举，但出人意料地是**数组分割字符串**似乎不支持换行`/n`的使用。

另外这个插件仍然无法进行登录，无论哪种方式。

如果可能的基础上可以将插件使用过程中搜索到的文件类型进行图标映射，对此只是个人建议。

希望你能帮我解决这个问题，感谢你开发的这款好用的豆瓣插件，希望这个插件越来越好。

**Comment by Wanxp** [comment]
现在默认的设置已支持frontmatter yaml 语法的数组形式。
数组现在也支持了以下的方式:
数组首， 数组元素首，数组元素分隔符，数组元素尾，数组尾，字符的指定

**Comment by logan00000000** [comment]
> 现在默认的设置已支持frontmatter yaml 语法的数组形式。 数组现在也支持了以下的方式: 数组首， 数组元素首，数组元素分隔符，数组元素尾，数组尾，字符的指定
感谢大佬支持
