### ISSUE TITLE
感谢提供丰富的影视类型，但似乎缺少了`记录片`

### ISSUE THREAD

**Issue by logan00000000** [Wanxp/obsidian-douban#76]

**Comment by logan00000000** [comment]
还有`名人`类型，对于学习电影的同学这是很必要的

**Comment by logan00000000** [comment]
漫画

**Comment by logan00000000** [comment]
动漫

**Comment by Wanxp** [comment]
每个类型能否提供 对应的 影视剧名称案例

**Comment by logan00000000** [comment]
> 每个类型能否提供 对应的 影视剧名称案例

`名人类型`
---
Title: "[[刘慈欣]]"
Alias: "[[Cixin Liu]],[[大刘]]"
Url: "https://www.douban.com/personage/27484095/"
CreateTime: "[[2023-10-18]]"
OriginalName: "[[刘慈欣]]"
DoubanId: 27484095
DateBirth: "[[1963-06-23]]"
PlaceBirth: "中国-山西-阳泉"
Introduction："中国当代科幻小说的主要代表作家，被誉为中国科幻文学的领军人物。中国科普作家协会会员，中国作家协会会员，山西省作家协会会员，2013年中国作家富豪榜上榜作家。自上世纪九十年代开始发表科幻作品，曾于1999年至2006年连续八年获得中国科幻银河奖，作品因宏伟大气、想象绚丽而获得广泛赞誉。他的科幻小说成功地将极端的空灵和厚重的现实结合起来，同时注重表现科学的内涵和美感，兼具人文的思考与关怀，努力创造出一种具有中国特色的科幻文学样式。出生于1963年6月，祖籍河南，山西阳泉长大，1985年毕业于华北水利水电学院（现华北水利水电大学）水利工程系，后于山西娘子关电厂任计算机工程师。刘慈欣长期关注科幻并尝试写作，他的风格多次变换，直到90年代中期才逐渐定型，并开始赢得读者的喝彩。1999年发表第一篇作品──短篇小说《鲸歌》，同年首次以短篇小说《带上她的眼睛》获得中国科幻银河奖一等奖；2000年《流浪地球》获中国科幻银河奖特等奖。刘慈欣迄今为止最重要的作品“三体三部曲”（原名“地球往事三部曲”）更是备受读者与媒体的赞誉，被普遍认为是中国科幻文学的里程碑之作，将中国科幻推上了世界的高度。"
Type: "Person"
MyRating: 
Status: "Pending"
Due: ""
Priority: 
Tags: 
---
### 人物简介
***
"中国当代科幻小说的主要代表作家，被誉为中国科幻文学的领军人物。中国科普作家协会会员，中国作家协会会员，山西省作家协会会员，2013年中国作家富豪榜上榜作家。自上世纪九十年代开始发表科幻作品，曾于1999年至2006年连续八年获得中国科幻银河奖，作品因宏伟大气、想象绚丽而获得广泛赞誉。他的科幻小说成功地将极端的空灵和厚重的现实结合起来，同时注重表现科学的内涵和美感，兼具人文的思考与关怀，努力创造出一种具有中国特色的科幻文学样式。出生于1963年6月，祖籍河南，山西阳泉长大，1985年毕业于华北水利水电学院（现华北水利水电大学）水利工程系，后于山西娘子关电厂任计算机工程师。刘慈欣长期关注科幻并尝试写作，他的风格多次变换，直到90年代中期才逐渐定型，并开始赢得读者的喝彩。1999年发表第一篇作品──短篇小说《鲸歌》，同年首次以短篇小说《带上她的眼睛》获得中国科幻银河奖一等奖；2000年《流浪地球》获中国科幻银河奖特等奖。刘慈欣迄今为止最重要的作品“三体三部曲”（原名“地球往事三部曲”）更是备受读者与媒体的赞誉，被普遍认为是中国科幻文学的里程碑之作，将中国科幻推上了世界的高度。"

### 作品：
***
#### 图书
***
>[[三体]],[[球状闪电]],[[流浪地球]]....

#### 音乐
****
>

#### 影视
***
>[[流浪地球]]
>[[流浪地球2]]
>[[流浪地球3]]

**Comment by logan00000000** [comment]
> 每个类型能否提供 对应的 影视剧名称案例

`纪录片`
人与自然 (1994)
Link："https://movie.douban.com/subject/27140070/"

`动漫`
Link："https://movie.douban.com/subject/2057171/"

**Comment by logan00000000** [comment]
> 每个类型能否提供 对应的 影视剧名称案例

另外豆瓣对`漫画`格式似乎没有涉猎
再次感谢作者辛勤付出，我昨晚还在想自学typescrip帮助作者开发，从0开始到上手开发之间还有很长时间
因此抱歉提供这么刁钻的需求。

**Comment by Wanxp** [comment]
纪录片、动画 这在豆瓣都是归为电影或者电视剧，没有单独的纪录片类型的条目。像你提到的《人与自然 (1994)》、《银魂》都是属于电视剧，都可以正常导入。如果你想从导入的内容中查看出是那种类型的可以关注genre字段，这个字段会说明具体是哪种类型的。

**Comment by Wanxp** [comment]
豆瓣是有人物类型条目的，这个可以未来开发下   ![1697599337770](https://github.com/Wanxp/obsidian-douban/assets/26840810/a3ccaff2-9431-4c8e-b4c2-f53c7dd3cb35)

**Comment by Wanxp** [comment]
> > 每个类型能否提供 对应的 影视剧名称案例
> 
> 另外豆瓣对`漫画`格式似乎没有涉猎 再次感谢作者辛勤付出，我昨晚还在想自学typescrip帮助作者开发，从0开始到上手开发之间还有很长时间 因此抱歉提供这么刁钻的需求。

加油！
