### ISSUE TITLE
自定义参数{{params}}无法引用！

### ISSUE THREAD

**Issue by Bananadurian** [Wanxp/obsidian-douban#78]
Platform：Win10
Obsidian Version：v1.4.14
Plugin Version：v1.9.3
Bug描述：
1. 添加自定义参数 `folderName` 后，在【笔记名称】中以路径 ` /Y-Life/{{folderName}}/{{title}}` 引用参数失效；
2. 自定义参数的【参数值】中引用参数失效。
![image](https://github.com/Wanxp/obsidian-douban/assets/53225469/c06ae6c5-9d0c-48e6-a784-612531bed9c9)
![image](https://github.com/Wanxp/obsidian-douban/assets/53225469/a8df4828-7f50-4710-a510-0bd80e57d556)

> **备注：插件旧版本不存在此问题！**

**Comment by Wanxp** [comment]
1.9.4版本修复了该问题

**Comment by Wanxp** [comment]
长时间未回复，关闭issues

**Comment by Bananadurian** [comment]
> 长时间未回复，关闭issues

👍1.9.4 已确认问题修复！
