### ISSUE TITLE
无法正常搜索电影

### ISSUE THREAD

**Issue by pyj419** [Wanxp/obsidian-douban#86]
1. 问题说明

1.1 操作:
创建文档时，无法正常搜索想看的电影。比如“肖申克的救赎”，点击搜索后，会出现空白搜索结果，仅有[下一页]选项。点击[下一页]后，搜索到的都是同名的其他很偏的电影，没有想要的结果。

1.2 结果:
![Uploading 截屏2023-12-15 00.52.02.png…]()
![Uploading 截屏2023-12-15 00.52.09.png…]()

5. 操作系统版本
- [ ] windows
- [ ] ubuntu
- [x] mac
- [ ] android
- [ ] ios
6. obisidian版本
ob为1.4.16，插件为1.9.6

**Comment by Xie-Zhixuan** [comment]
我在如下环境也出现同样的错误：windows 11 ，ob版本 1.4.16，插件版本 1.9.6

**Comment by Shukyo** [comment]
Same issue, any solution?

**Comment by anschein** [comment]
搜索书籍也是同样的情况，豆瓣改机制了？

**Comment by Shukyo** [comment]
> 搜索书籍也是同样的情况，豆瓣改机制了？

但是点击下一页可以显示内容，而第二页没有“上一页”的点击选项，所以应该还是能读取豆瓣内容的

**Comment by anschein** [comment]
> > 搜索书籍也是同样的情况，豆瓣改机制了？
> 
> 但是点击下一页可以显示内容，而第二页没有“上一页”的点击选项，所以应该还是能读取豆瓣内容的

比如我搜卡片笔记法，能够直接在豆瓣上搜到，但是用插件搜点了下一页出来的都不是正确的结果

**Comment by Shukyo** [comment]
> > > 搜索书籍也是同样的情况，豆瓣改机制了？
> > 
> > 
> > 但是点击下一页可以显示内容，而第二页没有“上一页”的点击选项，所以应该还是能读取豆瓣内容的
> 
> 比如我搜卡片笔记法，能够直接在豆瓣上搜到，但是用插件搜点了下一页出来的都不是正确的结果

是不是第一页理论上是有内容的，但是没有正确显示出来，第二页一般都是相关性较弱的结果，所以没有正确结果

**Comment by Wanxp** [comment]
好的，已收到反馈，我今天尝试下修复这个问题

**Comment by logan00000000** [comment]
同样的问题，但是通过导演名字搜索挺精准了

**Comment by Wanxp** [comment]
1.9.7 版本修复该问题

**Comment by Wanxp** [comment]
问题已修复
