### ISSUE TITLE
[Bug]:键入名称的交互窗口，疑似出现UI布局混乱

### ISSUE THREAD

**Issue by logan00000000** [Wanxp/obsidian-douban#88]
1. 问题说明

1.1 操作:
UI布局混乱

1.2 结果:
![image](https://github.com/Wanxp/obsidian-douban/assets/92864372/5d8a8a61-760c-4ddc-ba75-f27adba4f64a)

1.3 我想要的效果:

2. 操作系统版本
- [x] windows
- [ ] ubuntu
- [ ] mac
- [ ] android
- [ ] ios
6. obisidian版本
...

**Comment by Wanxp** [comment]
1.9.8修复该问题

**Comment by logan00000000** [comment]
> 1.9.8修复该问题

感谢付出
