### ISSUE TITLE
创立新笔记而不是插入当前笔记

### ISSUE THREAD

**Issue by zcysxy** [Wanxp/obsidian-douban#9]
谢谢开发这个插件！

我想提一个 feature request，即可以直接从命令创建笔记。我现在的工作流是，先创建一个空笔记，然后用插件搜索书/电影，再将信息插入当前笔记。我觉得一个更方便的流程是，我直接搜索书/电影，然后回车后插件自动创建笔记并插入信息。

**Comment by Wanxp** [comment]
与 #14 功能类似,相关讨论转移到这个issues #14 中了
