### ISSUE TITLE
[Bug]:移动端加载失败

### ISSUE THREAD

**Issue by peng1999** [Wanxp/obsidian-douban#94]
1. 问题说明

1.1 操作:

- 在移动端上面安装 obsidian-douban 
- 在社区插件页面启用 obsidian-douban

1.2 结果:
弹出消息显示 failed to load plugin obsidian-douban-plugin。
上诉操作在iOS和Android上皆可复现。

用Safari调试iOS app，给出报错信息：

- Plugin failure: obsidian-douban-plugin
   - TypeError: undefined is not an object (evaluating 'url.URL')
      - node_modules/follow-redirects/index.js
      - __require
      - anonymous
      - （匿名函数） — app.js:84290
      - （匿名函数） — app.js:10999
      - a — app.js:10905

看起来错误发生在 follow-redirects 这个依赖的头两行：

```js
var url = require("url");
var URL = url.URL;
```
~~但是我不太明白具体为什么会出错。~~
看起来原因是依赖了Electron，所以无法在移动端使用。

1.3 我想要的效果:
N/A

2. 书影音名称
N/A

3. 模板展示
N/A

4. 其它
N/A

5. 操作系统版本
- [ ] windows
- [ ] ubuntu
- [ ] mac
- [x] android
- [x] ios

6. obisidian版本
1.4.16 (114)

**Comment by urnotjl** [comment]
也遇到同样的问题，"Failed to load plugin obsidian-douban-plugin"
iPhone还能打开，iPad直接卡掉了。

**Comment by amitbha** [comment]
移动端很需要，经常会随手记下在看的书，现在只能在电脑上操作

**Comment by kangpou** [comment]
- Android Q
- Obsidian apk version 1.6.7
同样的问题，"Failed to load plugin obsidian-douban-plugin"，不知道大家安卓运行的如何。

**Comment by CyndiBoom9** [comment]
+1

**Comment by Wanxp** [comment]
本人node js不是很精通，所以移动端导入问题一直就悬着了。
现在的问题是移动端的obsidian所依赖的request 模块还不一样，同样的代码在pc端就能声响，移动端就不可以
比如以下获取数据的代码：
```js
require("follow-redirects").https.get(url, {...options}, function (response: any) {
				let chunks: any = [],
					size = 0;
				response.on("data", function (chunk: any) {
					chunks.push(chunk)
					size += chunk.length
				})

				response.on("end", function () {
					const data = Buffer.concat(chunks, size)
					resolve(new HttpResponse(response.statusCode, response.headers, data))
				})
			})

```

**Comment by luckyfatpig** [comment]
一样的问题，android 14
