### ISSUE TITLE
[Feature]: Dataview显示封面

### ISSUE THREAD

**Issue by DelmarHuang** [Wanxp/obsidian-douban#97]
你好，非常感谢这个作品。太好用了！就是有个小事情想请教下。

是这样的，如果我想用dataview筛选后显示封面，我需要像这样写：
```dataview
Table Without ID ("![|100](" + cover_url + ")") as Cover
From #book 
```

然后我看到你有个参数是“imageData.url”，但这个参数并没有出现在默认模板的属性里。现在默认使用的模板是把封面直接抓到正文里。所以我的理解是基于现在的情况，我是没法把它修改成如下代码展示封面的，对吗？

```dataview
Table Without ID ("![|100](" + imageData.url + ")") as Cover
From #book 
```

还是有办法呀？

如果确实没办法的话，那是不是说如果我需要用上面的代码显示封面的话，我需要先改模板（把imageData.url这个参数加到属性里），然后重新抓取书籍、电影啥的，再用上面的代码展示封面呢？

麻烦您看看我理解的对吗，感恩！

**Comment by Wanxp** [comment]
你是否按照以下方式处理的：
1. 模板 frontmatter中包含imageData.url参数
````md
---
imageUrl: {{imageData.url}}
---
```
2. 导入书影音
3. 汇总使用Dataview
````md
```dataview
Table Without ID ("![|100](" + imageUrl + ")") as Cover
From #book 
```
````

**Comment by Wanxp** [comment]
长时间没反馈，关闭问题
