### ISSUE TITLE
[Feature]:希望可以自定义自动增加的book/movie等tag

### ISSUE THREAD

**Issue by luaotix** [Wanxp/obsidian-douban#99]
首先感谢付出，发现这款插件如获至宝！
其次我在使用中发现，使用myTags后会自动增加book/movie，且未看到可修改的地方？
个人比较习惯全中文的界面，所以更希望能看到「书籍」「电影」这样的标签，希望可以自定义，谢谢。

另一个建议是，如果出现字段为空时，直接删除该字段，而非留空在那。
比如「原作名」，这对外国书籍较为有用，但国内书籍就不存在了，留个空在那也无意义。

再一个建议，豆瓣书籍的「datePublished」字段仅到月份，使用之后会自动补上「-01」的日期，这是无意义的，所以如果能和豆瓣一样仅有年月就更好了。

再次感谢！

**Comment by Wanxp** [comment]
在设置中有自定义参数，通过自定义参数 设置自己的值，然后在模板中引用参数

**Comment by Wanxp** [comment]
> 再一个建议，豆瓣书籍的「datePublished」字段仅到月份，使用之后会自动补上「-01」的日期，这是无意义的，所以如果能和豆瓣一样仅有年月就更好了。
这个作为bug后续处理
